#+STARTUP: hidestars

General changelog for listing changes starting from v0.0.4 and up.

* 0
*** 0
***** 4
      Major changes include:

     - splitting nisp-safe from nisp
     - removing metatilities as a dependency from nisp-safe
     - add dependency on cl-walker to nisp-safe. This is not used yet but is
       very likely to be used in the near future.
     - nisp-introspect has been moved into the nisp-safe system for now. The
       future of this one generic method system is uncertain. It is very
       likely not required and was written before I knew some things.
     - nispbot is now an object that superclasses connection
     - nisp-safe now works with objects
     - stub of new test framework focused on functional programming started.
     - many other changes, see changelog for reference [2009-12-22 Tue]

     * Additional note: admin eval was added somewhere around this
       release. [2009-12-25 Fri] 

***** 5
      Tests sort of run, no way to automatically verify the results yet,
      but its possible to add tests to a fbound symbol, remove them, map
      over them/run them returning the results and get a list of all
      fbound symbols with a test on them.

      - functional-tests
        - Added deftype fbound
        - Added is-set-equalp
        - Added fbound-plist-test-p
        - Added remove-fbound-plist-test
        - Added add-fbound-plist-test
        - Added clear-fbound-plist-test
        - Modified set-fbound-plist-tests
          - Removed (declare ...) and (the ...) and placed them in an
            ftype instead of inside the function proper.
        - Mdified make-io-set
          - Type checks were added to the io-set class, and they failed
            when the io-set was created with :output output where output
            was nil.
        - Added find-tested-symbols
          - Pass a keyword, symbol, or package and get a list of symbols
            that have tests on them. This works for the plist tests only
            right now. [2009-12-24 Thu]
            
***** 6
******* functional-tests
        - Remove add-test-to-plist
          - Replaced by add-fbound-plist-test.
        - Remove _function-test_ class
          - Has no use as we use symbol plists instead of a seperate
            class now. Makes the chore of tracking tests easier to just
            associate with the function being tested directly
        - Remove make-function-test
        - Remove some specializers of run-test-set
        - Remove _define-function-test_
          - Macro for function-test creation, not used anymore since
            function-test is gone.
        - Remove add-test-set
        - Remove add-test-to-plist
          - This was largely useless as it could only add one test.
        - Add class [[io-log]]. [2009-12-24 Thu]

***** 7
******* functional-tests
        - Change [[run-test-set]]
          - Argument order swapped so the set describing the test is
            specified first, then the object to test.
        - Add [[make-io-actual-result]]
          - Largely will be used to track the start of the test and
            operate with the results of the test. This is the object
            that will get stored in [[io-log]].
        - Add [[log-test-result]]
          - Generic function that takes a test result object and stores
            it in the io-set object's io-log object. Two primary methods
            defined.
            - IO-LOG IO-ACTUAL-RESULT
            - IO-SET IO-ACTUAL-RESULT
        - Rename [[map-plist-tests]] --> [[run-test-set]]
          - Right now does the same thing, just with a more logical
            name. [2009-12-24 Thu]

***** 8
******* functional-tests
        - Add [[compare-last-test-result]]
          - Method args: IO-SET
            - Return t on test pass and nil on test failure
          - Method args: FBOUND
            - Return a list of test results.
        - Add slot end-time to [[io-actual-result]]
          - Old run-time is now end-time, runtime is the difference
            between creation-time and end-time.
        - Remove slot run-time from [[io-actual-result]]
          - We can compute this by taking end-time - start-time.
        - *Rename* _io-actual-result_ -> [[io-result]]
          - Lets do this now before any api starts settling in. Its
            clearer this way rather then messing with the distinction
            between io-expected-result and io-result. Just remember that
            io-result is the interesting part, eg with test results.
        - Remove \*functional-tests-list\*
          - Not needed anymore as we don't want to restrict ourselves to
            just one global tests list. Since we removed function-test
            last revision this variable does not really have a good use
            anymore.[2009-12-25 Fri]

******* Notes/Tasks
        Irrelevant to actual development progress, but the notes.org
        file has been split out into tasks.org. [2009-12-25 Fri]

***** 9
******* functional-tests
        - Add [[last-test-result]]
          - Add method: (IO-LOG)
        - Add [[run-time]]
          - Add method: (IO-RESULT)
          - Add method: (IO-LOG)
          - Add method: (IO-SET)
          - Add method: (FBOUND)
          - Add method: (PACKAGE)
          - Add method: (LIST)
        - Add [[single]]

***** 10
******* functional-tests
        - Modify [[last-test-result]]
          - Add method: (IO-SET)
            - Direct 1 to 1 relationship with IO-LOG
          - Add method: (IO-RESULT)
            - Degenerate case
          - Add method: (FBOUND)
          - Add method: (PACKAGE)
          - Add method: (LIST)
        - Modify [[run-fbound-set]]
          - Add method: (PACKAGE)
            - Run all tests in the given package. Probably will not do
              what would be reasonably expected yet.
        - Modify [[io-set]]
          - Add slot: test
            - What test to perform to determine if a test passes or not.
        - Remove [[clear-fbound-plist-test]]
          - No real use, not using it is actually shorter then using it.

******* nisp.ldap
        Import from eighthbit-website
        - Modify [[*default-host*]]
          - Spelling mistake corrected: localhsot to localhost

******* nispbot
        - Add [[safe-closure::ldap-entry]]

***** 11
******* functional-tests
        - Modify [[io-set]]
          - Add slot: expected-result
          - Remove slot: test
          - No longer inherit from io-expected-result
        - Modify [[io-expected-result]]
          - Add slot: test
        - Modify [[make-io-set]] to use [[make-io-expected-result]] instead of
          filling in slots that [[io-set]] no longer has.
          - Arguments signal and output default to ""
          - Add key: fbound
            - This defaults to nil and is intended to contain the
              function name that the tests are against. Not strictly
              required but having it makes remembering the function
              being tested against much easier then passing it around.
        - Modify [[make-io-expected-result]]
          - Arguments signal and output default to ""
        - Modify [[compare-last-test-result]]
          - Since the location of the expected result moved, move the
            compare check with it.
        - Add [[result-equal-p]]
          - This is the underlaying method that we will use to select
            predicates to apply on test results. Right now it works with
            the function 'equal.

***** 12      
******* Split ldap out                                           :nisp_ldap:
        This got split out into nisp.8b-ldap and nisp.ldap. The general
        ldap helpers are in nisp.ldap, anything specific to 8b is in
        that package. This also got spun out into its own
        submodule. I'll still be doing changelogs of submodules here in
        the primary nisp package.

******* No more dependency on metatilities                   :nispbot:nisp:
        This is finally removed, build time is now about one second as
        compared to the approx 7 or 8 for metatilities to do its thing.
        
***** 13
******* asdf/ added
        This directory is full of symlinks to various dependencies and
        nisp system definitions. The idea here is you can add this
        directory to your asdf:*central-registry* sorta like this:
        : (pushnew "/home/nixeagle/lisp/nisp/asdf/" asdf:*central-registry* :test #'equal)

        The advantage here is no symlinking is required.

******* submodules
        Various portions of the nisp codebase got split out into
        seperate submodules as they are not directly part of each
        other. Additinally submodules for hu.dwim packages were added
        after importing them from darcs.

********* nisp.nistilities
          These are my general utilities that do not depend on anything
          else. The whole point is the functions defined here are self
          contained.

********* hu.dwim packages
          These packages caused me a considerable amount of grief. None
          of these are asdf installable. The location of these packages
          are contained within the various repositories. Their primary
          site is [[http://dwim.hu/][dwim.hu]]. For a bit I was very confused as it defaults
          to hungarian unless you have javascript enabled. Listed below
          are packages I forked for the purpose of submoduling them.

          - hu.dwim.def
          - hu.dwim.defclass-star
          - hu.dwim.common-lisp
          - hu.dwim.asdf
            - _why_ is there this package?
          - hu.dwim.walker
            - The whole reason I had to do this ;). Not using it yet,
              but I plan to.
            - Please note that this is _not_ a direct mirror of the
              darcs repository. See next line.
          - A single function from hu.dwim.util which is now contained
            in nisp.dwim.handle-otherwise
            - It was very curious to me that hu.dwim.walker depends on
              hu.dwim.util for just this one function. I split it out
              because hu.dwim.util has an insane number of dependencies
              and requiring all of those dependencies for a single
              function that does not depend on anything other then
              hu.dwim.def seemed to me to be a bit on the absurd side.

***** 14
******* Missed dwim.defclass-star
        I added the submodule, but forgot to require it.
******* Change *default-host* to *admin-hosts*
        =*default-host*= is now depreciated. =*admin-hosts*= is a list.
******* nispbot moved to irc-bot/
        This includes the following files:
        - config-dist.lisp
        - config.lisp
        - nispbot.lisp
        - nispbot-tests.lisp
******* depend on alexandria
        - Required for random-elt. Dependency is alright as it does not
          have any more dependencies of its own, plus its a general purpose library
          all in the public domain.
