* TODO Shadowing import stuff
move from import-from to shadowing-import-from for all packages using
define-export-system. This lets us be one step removed from the common
lisp package and limits damage to the overall (lisp) system should
something manage to


* TODO Sandbox level segragation
I should be able to create sandboxes with different sets of imports
and use different ones depending on who is accessing them.


* TODO Rename safe-external package to something else
As it stands the name implies these are external to the safe
package. Most of what is in here are variables and functions directly
related *to* safe. As such the name is a misnomer.

* TODO Define a useful documentation function
Right now documentation is dependent on swank.

* DONE Enable test again for nistilities
  CLOSED: [2009-12-15 Tue 21:00]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2009-12-15 Tue 21:00]
  :END:
Both nisp and nistilities tests

Use (lift:run-tests :suite 'test-mixin). However I need to generate one
of those that is specific only to nisp related stuff. mixin seems to run
all defined test-suites no matter what project is associated with them.
