
* Safety
Section for general issues and notes with respect to keeping the system
safe for arbitrary code execution.

*** *readtable* in package
    It is probably not a very good idea to put this in the package
    itself and instead associate the readtable with the wrapper object
    safe-package. If the readtable is not stored in the package itself
    or the readtable is somehow made into a constant that cannot be
    changed ever inside the package... we should be safe.



* TODO Shadowing import stuff
move from import-from to shadowing-import-from for all packages using
define-export-system. This lets us be one step removed from the common
lisp package and limits damage to the overall (lisp) system should
something manage to


* TODO Sandbox level segragation
I should be able to create sandboxes with different sets of imports
and use different ones depending on who is accessing them.





* WAIT Implement symbol->string
  :LOGBOOK:
  - State "WAIT"       from "TODO"       [2009-12-16 Wed 19:49] \\
    Passing on this for the time being, I really would like to avoid having
    to do more string manipulation then strictly needed with respect to
    packages and symbols.
  :END:
Basic idea is taking any symbol and returning a string with a specified
package (defaulting to current one), and the name of the symbol.


* BUG Changing symbol names too much
To the bot this should work:
: ? (documentation 'list 'function)

We get 
: ? (DOCUMENTATION 'LIST '|SAFE-nixeagle::EighthBit::staff|::FUNCTION)
instead

* DONE Make CL-WALKER ASDF installable
  CLOSED: [2009-12-24 Thu 20:36]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2009-12-24 Thu 20:36]
  :END:
  At least give it a system definition.
  - Never had to be done





