* Notes
*** Safety
Section for general issues and notes with respect to keeping the system
safe for arbitrary code execution.

*** *readtable* in package
    It is probably not a very good idea to put this in the package
    itself and instead associate the readtable with the wrapper object
    safe-package. If the readtable is not stored in the package itself
    or the readtable is somehow made into a constant that cannot be
    changed ever inside the package... we should be safe.



* Ideas
*** General ideas


*** Functional Tests
*** Possible test form
(test list
      (input 1 2 3 4 output 1 2 3 4)
      (input 1 2 output 1 2))

(test list
      (input (1 2 3 4) output (1 2 3 4))
      (input (1 2) output (1 2)))






* Submodules
  cl-walker is interesting because its in a darcs repo. Right now I have
  a copy of the darcs repo at ~/lisp/darcs-cl-walker/

  The command to update this from ~/lisp is:
  : ~/repos/bzr-fastimport/exporters/darcs/darcs-fast-export darcs-cl-walker/hu.dwim.walker_0/ |(cd cl-walker.git; git fast-import)

  Then cd to ~/lisp/cl-walker/ and do:
  : git pull
  : git push github master

  Then go to ~/lisp/nisp/
  : git submodule update
  : git commit -m "updated cl-walker"
  : git push


* TODO Make :hu.dwim.asdf a submodule

  : darcs get http://dwim.hu/darcs/hu.dwim.asdf/


* Depend on :contextl :depend:
  asdf installable. One error I had to tell sbcl 1.0.34 to ignore.

* Depend on :anaphora :depend:
Some quick notes

* Dependencies
  Need svn cl-irc, not the latest tarball!
  : svn checkout svn://common-lisp.net/project/cl-irc/svn

*** cl-ldap
    - [ ] gentoo linux
    - [X] FBSD8
      - It and all its dependencies compiled without one error in sbcl
        1.0.31
