
* DONE TRIVIAL-TIMEOUT style-warning :ARCHIVE:
-+  style-warning (1)
 `-- The variable COM.METABANG.TRIVIAL-TIMEOUT::C is defined but never used.
-+  warning (1)
 `-- COMPILE-FILE warned while performing #<COMPILE-OP NIL {100617AD41}> on
     #<CL-SOURCE-FILE "nispbot" {1004A69201}>.

* BUG Clozure drops to debugger on nispbot input
  Not totally sure why atm, needs fixed at some point. The problem is
  the timeout seems to also abort the debugger which is different
  behavior then with sbcl.

* TODO Define property-list type :ARCHIVE:
  Verify input is a property list etc.

  Huh?
* DONE Split functional-tests from nisp :ARCHIVE:
  DEADLINE: <2010-01-05 Tue> CLOSED: [2010-04-22 Thu 18:00]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2010-04-22 Thu 18:00]
  :END:
  :PROPERTIES:
  :CREATED:  <2010-01-03 Sun 07:31>
  :END:
  This is starting to become independent of :nisp itself. I don't want
  to force others to pull in all of nisp for just that framework.

  Update: Now has its own asd definition, needs to be split into its own
  repository at some point in the future.


* TODO Some kind of a str (string) command... :nisp:lisp:strings:
  I'd like something better then doing (format nil "blah ~A" stuff)... and
  concatenate just does not fit my fancy.

