(in-package :nisp.mop-simple)

(macrolet ((define-mop (name)
             `(progn
                (defgeneric ,name (class))
                (defmethod ,name ((class class))
                   (,(alexandria:ensure-symbol name :closer-mop) class))
                (defmethod ,name ((instance standard-object))
                   (,name (class-of instance)))
                (defmethod ,name ((class symbol))
                   (,name (find-class class)))
                (defmethod ,name ((class string))
                   (,name (find-symbol class))))))
  (define-mop class-default-initargs)
  (define-mop class-direct-default-initargs)
  (define-mop class-slots)
  (define-mop class-direct-slots)
  (define-mop class-direct-subclasses)
  (define-mop class-direct-superclasses)
  (define-mop class-finalized-p)
  (define-mop class-precedence-list)
  (define-mop class-prototype)
  (define-mop compute-class-precedence-list)
  (define-mop compute-default-initargs)
  (define-mop compute-slots)
  (define-mop finalize-inheritance))

(macrolet ((define-mop (name)
             `(progn
                (defgeneric ,name (generic-function))
                (defmethod ,name ((generic-function standard-generic-function))
                  (,(alexandria:ensure-symbol name :closer-mop)
                    generic-function))
                (defmethod ,name ((generic-function symbol))
                  (,name (symbol-function generic-function)))
                (defmethod ,name ((generic-function string))
                  (,name (find-symbol generic-function))))))
  (define-mop generic-function-argument-precedence-order)
  (define-mop generic-function-declarations)
  (define-mop generic-function-lambda-list)
  (define-mop generic-function-method-class)
  (define-mop generic-function-method-combination)
  (define-mop generic-function-name)
  (define-mop generic-function-methods))

;;; End